[toolchain]
channel = "nightly" # rustc 1.77.0-nightly (ef71f1047 2024-01-21)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src", "rust-docs"]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]
